In [24]:
#tsv파일 pandas로 데이터프레임 확인
import pandas as pd
df = pd.read_csv('gutenberg_books.tsv', sep='\t')

In [25]:
df

,ID,Title,Author,Year,Text
0,84,"Frankenstein; Or, The Modern Prometheus",Mary Wollstonecraft Shelley,1993,"The Project Gutenberg eBook of Frankenstein, b..."
1,1342,Pride and Prejudice,Jane Austen,1998,The Project Gutenberg eBook of Pride and preju...
2,2701,"Moby Dick; Or, The Whale",Herman Melville,2001,The Project Gutenberg eBook of Moby-Dick; or T...
3,1513,Romeo and Juliet,William Shakespeare,1998,The Project Gutenberg eBook of Romeo and Julie...
4,145,Middlemarch,George Eliot,1994,"The Project Gutenberg eBook of Middlemarch, by..."
...,...,...,...,...,...
883,2048,The Sketch-Book of Geoffrey Crayon,Washington Irving,2000,The Project Gutenberg EBook of The Sketch Book...
884,1642,Euthyphro,Plato,1999,"The Project Gutenberg EBook of Euthyphro, by P..."
885,6923,The Miser,Molière,2004,The Project Gutenberg eBook of The Miser (L'Av...
886,2151,The Works of Edgar Allan Poe — Volume 5,Edgar Allan Poe,2000,The Project Gutenberg eBook of The Works of Ed...
887,17957,On the Sublime,active 1st century Longinus,2006,"The Project Gutenberg EBook of On the Sublime,..."

In [19]:
# Author에서 balzac 검색
df[df['Author'].str.contains('balzac', case=False)]

Empty DataFrame
Columns: [ID, Title, Author, Year, Text]
Index: []